### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Cynix32** [LukeGrahamLandry/cultivated-snacks-mod#1]
I do not have time to extensively test this because life, however, removing this mod makes the crash go away. This crash happens when loading a world, patchouli enabled.

CRASHLOG: https://pastebin.com/cgZq5ydG

No optifine
MC 1.16.5
Forge 36.2.19
Thermal Cultivation and other thermal mods also installed
Java 8
cultivated-snacks-1.08.jar

**Comment by LukeGrahamLandry** [comment]
thanks for letting us know! shall be fixed later this week :)

**Comment by Cynix32** [comment]
Downloading the latest update posted on curseforge fixed the crash. Thanks for the fix, closing issue.
